version: 2.1

references:
    - &container_config
        macos:
            xcode: "14.2.0"
        working_directory: /Users/distiller/project
        shell: /bin/bash --login -eo pipefail

commands:

    save_workspace:
      parameters:
        path:
          type: string
          default: .
      steps:
        - persist_to_workspace:
            root: .
            paths:
              - << parameters.path >>

    restore_workspace:
      steps:
        - attach_workspace:
            at: .

    gems:
      steps:
        - restore_cache:
            key: &gems_cache_key 1-gems-{{ checksum "Gemfile.lock" }}
        - run:             
            name: Bundle Install
            command: bundle check --path=.vendor/bundle || bundle install --path=.vendor/bundle --jobs=4 --retry=3
        - save_cache:
            key: *gems_cache_key
            paths:
              - .vendor/bundle

    cocoapods:
        steps:
            - restore_cache:
                key: &cocoapods_cache_key 3-pods-{{ checksum "Podfile.lock" }}
            - run:
                name: Pod Install
                command: |
                    if ! diff -q Podfile.lock Pods/Manifest.lock &>/dev/null; then
                        curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
                        bundle exec pod install || bundle exec pod install --repo-update
                    fi
            - save_cache:
                key: *cocoapods_cache_key
                paths:
                    - Pods

    carthage:
        steps:
            - restore_cache:
                key: &carthage_cache_key 101-carthage-{{ checksum "Cartfile.resolved" }}
            - run:
                name: "Bootstrap Carthage"
                command: |
                    carthage bootstrap --no-build
            - save_cache:
                key: *carthage_cache_key
                paths:
                    - Carthage

jobs:

    checkout_code:
      <<: *container_config
      steps:
        - checkout
        - gems
        - carthage
        - save_workspace

    test:
        parameters:
            parameters:
                type: string
        <<: *container_config
        steps:
            - restore_workspace
            - gems
            - run: script/test << parameters.parameters >>
    
    cocoapods_validation:
        <<: *container_config
        steps:
            - restore_workspace
            - gems
            - cocoapods
            - run: pod lib lint --use-libraries
    
    spm_validation:
        <<: *container_config
        steps:
            - restore_workspace
            - run:
                command: |
                    swift --version
                    swift build
                    swift test
    
workflows:
    version: 2

    build:
        jobs:
            - checkout_code
            - test:
                parameters: iphonesimulator "platform=iOS Simulator,name=iPhone 11" ReactiveFeedback-iOS
                name: Test-iOS
                requires:
                    - checkout_code
            - test:
                parameters: macosx "arch=x86_64" ReactiveFeedback-macOS
                name: Test-macOS
                requires:
                    - checkout_code
            - test:
                parameters: appletvsimulator "platform=tvOS Simulator,name=Apple TV 4K" ReactiveFeedback-tvOS
                name: Test-tvOS
                requires:
                    - checkout_code
            - test:
                parameters: iphonesimulator "platform=iOS Simulator,name=iPhone 11" Example build
                name: ExampleApp
                requires:
                    - checkout_code
            - cocoapods_validation:
                requires: &all_tests
                    - Test-iOS
                    - Test-macOS
                    - Test-tvOS
                    - ExampleApp
            - spm_validation:
                requires: *all_tests
